[package]
name = "BasicCoin"
version="0.0.0"
[addresses]
My="_"
[dev-addresses]
My="0x2"
Std="0x1"
[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git", subdir="language/move-stdlib", rev = "56ab033cc403b489e891424a629e76f643d4fb6b"}